INSERT OR IGNORE INTO stocks (symbol, name, sector) VALUES
('AADS', 'AngloGold Ashanti Ghanaian Depository Shares', 'Mining'),
('ACCESS', 'Access Bank Ghana', 'Banking'),
('ADB', 'Agricultural Development Bank', 'Banking'),
('AGA', 'AngloGold Ashanti Limited', 'Mining'),
('ALLGH', 'Atlantic Lithium Ltd', 'Mining'),
('ALW', 'Aluworks Ltd', 'Manufacturing'),
('ASG', 'Ashante Gold Corporation', 'Mining'),
('CLYD', 'Clydestone (Ghana) Limited', 'Real Estate'),
('CMLT', 'Camelot Ghana Ltd', 'Real Estate'),
('CPC', 'Cocoa Processing Company', 'Consumer Goods'),
('DASPHARMA', 'Dannex Ayrton Starwin PLC', 'Healthcare'),
('DIGICUT', 'Digicut Advertising & Production Limited', 'Media'),
('EGH', 'Ecobank Ghana Limited', 'Banking'),
('EGL', 'Enterprise Group Limited', 'Insurance'),
('ETI', 'Ecobank Transnational Incorporation', 'Banking'),
('FAB', 'First Atlantic Bank', 'Banking'),
('FML', 'Fan Milk Ltd', 'Consumer Goods'),
('GCB', 'Ghana Commercial Bank Ltd', 'Banking'),
('GGBL', 'Guinness Ghana Breweries Ltd', 'Consumer Goods'),
('GLD', 'NewGold Issuer Limited', 'Mining'),
('GOIL', 'Ghana Oil Company Limited', 'Oil & Gas'),
('HORDS', 'Hords Ltd', 'Trading'),
('IIL', 'Intravenous Infusions Limited', 'Healthcare'),
('KASA', 'Kasapreko PLC', 'Consumer Goods'),
('MAC', 'Mega African Capital Limited', 'Financial Services'),
('MMH', 'Meridian-Marshalls Holding Company Limited', 'Industrial'),
('MTNGH', 'MTN Ghana Ltd', 'Telecommunications'),
('PBC', 'Produce Buying Company Ltd', 'Agriculture'),
('RBGH', 'Republic Bank (Ghana) Limited', 'Banking'),
('SAMBA', 'Samba Foods Limited', 'Consumer Goods'),
('SCB', 'Standard Chartered Bank (Ghana) Ltd', 'Banking'),
('SCB-PREF', 'Standard Chartered Bank (Ghana) Ltd Pref', 'Banking'),
('SIC', 'SIC Insurance Company Limited', 'Insurance'),
('SOGEGH', 'Societe Generale Ghana Limited', 'Banking'),
('TBL', 'Trust Bank Limited (The Gambia)', 'Banking'),
('TLW', 'Tullow Oil PLC', 'Oil & Gas'),
('TOTAL', 'TotalEnergies Marketing Ghana', 'Oil & Gas'),
('UNIL', 'Unilever (Ghana) Ltd', 'Consumer Goods'),
('ZEN', 'Zen Petroleum Holdings', 'Oil & Gas');